version: '3.4'

services:

  docker-mongo:
    image: mongo:latest
    #container_name: mongo
    hostname: backend
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb


volumes:
  mongo-data:
  mongo-config:

networks:
  backend: