CREATE DATABASE testdb;

CREATE TABLE users (
id INT NOT NULL IDENTITY PRIMARY KEY,
full_name VARCHAR(100) NOT NULL,
sex CHAR(1) NOT NULL,
age INT NOT NULL,
hobby VARCHAR(100) NOT NULL DEFAULT '',
email VARCHAR(100) NOT NULL,
);